services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-clear
    environment:
      POSTGRES_USER: psql_limon4ik_user
      POSTGRES_PASSWORD: psql_limon4ik_password
      POSTGRES_DB: db
    ports:
      - "5434:5432"  # <= внешний порт 5434, внутри 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
